import React from "react";
import { Metadata } from "next";
import AboutPages from "./AboutPages";

export const metadata: Metadata = {
    title: "About | SIGO Express",
    description: "Generated by create next app",
};

const AboutPage = () => {
  return (
    <AboutPages />
  );
};

export default AboutPage;