import React from "react";
import { Metadata } from "next";
import LayananPages from "./LayananPages";

export const metadata: Metadata = {
    title: "Layanan | SIGO Express",
    description: "Generated by create next app",
};

const LayananPage = () => {
  return (
    <LayananPages/>
  );
};

export default LayananPage;