import React from "react";
import ContactPages from "./ContactPages"
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Contact | SIGO Express",
    description: "Generated by create next app",
};

const ContactPage = () => {
  return (
    <ContactPages/>
  );
};

export default ContactPage;